# Generated by Django 4.1.3 on 2023-05-29 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_alter_product_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='images')),
            ],
        ),
        migrations.AlterField(
            model_name='customer',
            name='email',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(blank=True, choices=[('Clothes', 'Clothes'), ('Shoes', 'Shoes'), ('Jewelry', 'Jewelry'), ('Cosmetics', 'Cosmetics'), ('Foods', 'Foods'), ('Furnitures', 'Furnitures'), ('Equiptments', 'Equiptments'), ('Books', 'Books'), ('Accessories', 'Accessories'), ('Electronics', 'Electronics'), ('Fashion', 'Fashion'), ('Parts', 'Parts')], max_length=20, null=True),
        ),
    ]
